### PR TITLE
Added option to scale animation in DrawAnimationFrame() and added JustFinished() function to Animation struct.

### PR DESCRIPTION
**Pull request by InvincibleMiller**
Great Job with your extensions by the way!

### CODE REVIEW

**Review by justinrichardsmusic — COMMENTED** [review]
Hi FalcoDJ,

I can see that you have been using (and made your modifications to) version 1.1... The current version is 1.5 and has scaling included and also has a "PlayNext" option which will trigger once the current animation finishes, in addition to a "PlayAfterSeconds" function as well...

If you would like to have a look through the current version and see if it already does what your require and let me know?  If not I will have a look at your suggestions and go from there :-)

Glad you found it useful!

Thanks,
Justin

**Comment by FalcoDJ** [comment]
Oh wow! I didn't realize I was so behind.

**Comment by FalcoDJ** [comment]
Every thing looks great! Only, I think the JustFinished() Function for animations is pretty useful; for instance I use it to change enemy states in a state machine for my project.

**Comment by justinrichardsmusic** [comment]
I've added the ability to test whether an animation has stopped on a given update frame and updated the repo...

**Pull request closed without merging**
